### ISSUE TITLE
Нет return в методах!

### ISSUE THREAD

**Issue by paladinbbk** [turbolukoshko/PHP-Hillel-IT#1]
https://github.com/turbolukoshko/PHP-Hillel-IT/blob/35cc7cca06b9df8b03898d7fe2f853cb535f429d/index.php#L17

**Comment by turbolukoshko** [comment]
<?php
/**
* 
*/
class Tasks{
	
	public function myNums ($arr){
	$result = [];
	for ($i=0; $i < $arr ; $i++) { 
		if ($arr % 2 == 0) {
			$result[] = $i++;
		}
	}
	return $result;
}
}

$obj = new Tasks;
var_dump($obj->myNums(24));

**Comment by turbolukoshko** [comment]
`<?php
/**
* 
*/
class Tasks{
	
	public function myNums ($arr){
	$result = [];
	for ($i=0; $i < $arr ; $i++) { 
		if ($arr % 2 == 0) {
			$result[] = $i++;
		}
	}
	return $result;
}
}

$obj = new Tasks;
var_dump($obj->myNums(24));`

**Comment by turbolukoshko** [comment]
`<?php
/**
* 
*/
class Tasks{
	
	public function myNums ($arr){
	$result = [];
	for ($i=0; $i < $arr ; $i++) { 
		if ($arr % 2 == 0) {
			$result[] = $i++;
		}
	}
	return $result;
}
}

$obj = new Tasks;
var_dump($obj->myNums(24));`

**Comment by paladinbbk** [comment]
ну залей в git. и закрой проблему
